### ISSUE TITLE
securityError on Internet Explorer

### ISSUE THREAD

**Issue by moatasem1** [22nds/coinhive#1]
Internet Explorer shows this error:
![error_screenshot](https://user-images.githubusercontent.com/22029917/39087800-927cf7dc-45a6-11e8-90ce-51b4b5f11977.PNG)

**Comment by 22nds** [comment]
I have updated the coinhive script and it now works on Firefox. Feel free to test in Explorer.

**Comment by moatasem1** [comment]
I still get the same error on Internet Explorer

**Comment by 22nds** [comment]
I would advise you to use some other browser as Explorer has a limited support for JavaScript Web Workers. More info on Web Workers https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker
